package com.arcxp.commons.throwables

import androidx.annotation.Keep

@Keep
enum class ArcXPSDKErrorType {
    INIT_ERROR,
    CONFIG_ERROR,
    SERVER_ERROR,
    INVALID_SESSION,
    RECAPTCHA_ERROR,
    LOGIN_ERROR,
    ONE_TIME_ACCESS_LINK_ERROR,
    REGISTRATION_ERROR,
    APPLE_CONFIG_ERROR,
    APPLE_LOGIN_ERROR,
    APPLE_LOGIN_CANCEL,
    FACEBOOK_LOGIN_ERROR,
    FACEBOOK_LOGIN_CANCEL,
    GOOGLE_LOGIN_ERROR,
    GOOGLE_LOGIN_ERROR_NO_ACCOUNT,
    GOOGLE_LOGIN_CANCEL,
    SEARCH_ERROR,
    EXOPLAYER_ERROR,
    SOURCE_ERROR,
    RENDERER_ERROR,
    VIDEO_STREAM_DATA_ERROR,
    NONCE_INITIALIZATION_ERROR
}